### ISSUE TITLE
Optimizations not enabled by default

### ISSUE THREAD

**Issue by justinsb** [ccutrer/mordor#16]
Optimizations don't seem to be enabled, at least on Linux (-O3 gives a big performance boost for me). 

Is there a reason why they're not on by default?  Should I be passing an extra configure argument?

**Comment by ccutrer** [comment]
it's simply autoconf defaults

configuring with --disable-assert CXXFLAGS='-g -O2' is the recommended configuration for a release build (disable asserts, optimize, but still include debugging symbols; they can be stripped later)
