### ISSUE TITLE
mordor crashes/assert failure on exit

### ISSUE THREAD

**Issue by kevincai** [ccutrer/mordor#7]
repro step
1. enable FILE log by: `export LOG_FILE=<your log file>`
2. enable all debug mask: `export LOG_DEBUGMASK=.*`
3. run any unit test: `./mordor/tests/run_tests Zlib.*`

You will get

terminate called after throwing an instance of 'boost::exception_detail::clone_implMordor::NativeException'
  what():  std::exception
Aborted

**Comment by ccutrer** [comment]
So the reason for the crash is that the global variables in fiber.cpp are being torn down before logging is torn down, and logging tries to access FLS, which then tries to bring Fibers back up, but fails because the globals have been torn down.

**Comment by kevincai** [comment]
yes, exactly.
